[package]
name = "traffic-director"
version = "0.1.0"
edition = "2024"

[dependencies]
ecdysis = "1.1.1"
foundations = "5.10.1"
rmqtt-codec = "0.3.0"
tokio = { version = "1.53.1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
futures = "0.3"
bytes = "1"
log = "0.4"
env_logger = "0.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
nix = { version = "0.26", features = ["socket", "process", "signal"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["full"] }
